// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vhoezhwolpruttchcmfy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZob2V6aHdvbHBydXR0Y2hjbWZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwODQxNTUsImV4cCI6MjA1ODY2MDE1NX0.V3AdR9CdsYnr6Pn0xtbPEHVi5uWTZgqMmJpRh911ZE8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);